version: "3.8"

services:
  dnd-viewer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    # Optional: Bind-Mount für lokale Charakterdateien
    volumes:
      - ./public:/app/public:ro
    networks:
      - dnd-network

networks:
  dnd-network:
    driver: bridge
# Optional: Für Reverse Proxy Setup
# services:
#   nginx:
#     image: nginx:alpine
#     ports:
#       - "80:80"
#       - "443:443"
#     volumes:
#       - ./nginx.conf:/etc/nginx/nginx.conf:ro
#       - ./ssl:/etc/nginx/ssl:ro
#     depends_on:
#       - dnd-viewer
#     networks:
#       - dnd-network
